[package]
name = "ai-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
ai-core = { path = "../core" }
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
async-stream = "0.3"