[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/anthropic", 
    "crates/agent",
    "examples",
]

[workspace.dependencies]
ai-core = { path = "crates/core" }
ai-anthropic = { path = "crates/anthropic" }
ai-agent = { path = "crates/agent" }